### ISSUE TITLE
Fairy | Deps: Upgrade `actions/cache`.

### ISSUE THREAD

**Issue by tomerle** [gamitee-dev/html-fairy#396]
### Motivation
1. We're too behind on too many GHA deps.
2. This also means too many PRs from dependabot to live with.

### TODO
1. Read and understand all relevant release notes.
2. If any change is required, please open a PR and do it.
3. End result will be merging #383.

**Comment by Ronensh110** [comment]
@tomerle What is the status with this one?

**Comment by tomerle** [comment]
@Ronensh110, tested myself. It's only the build process, and not the deploy, so we're cool. Declaring DONE.

_FYI, Fairy releases are anyway meaningless to you guys, and you will test it anyway when TinkerBell upgrades to a newer Fairy version._
